import { Router } from "express";

import assignmentsRoute from "./assignments/assignment.routes";
import catalogRoute from "./catalog/catalog.routes";
import residentsRoute from "./residents/residents.routes";
import contactsRoute from "./contacts/contacts.routes";
import uploadRoute from "./common/upload.routes";
import homeRoute from "./home/home.routes";
import incidentRoute from "./incidents/incident.routes";
import indexRoute from "./index.routes";
import kardexRoute from "./kardex/kardex.routes";
import locationsRoute from "./locations/locations.routes";
import maintenanceRoute from "./maintenance/maintenance.routes";
import recurringRoute from "./recurring/recurring.routes";
import reportRoute from "./reports/report.routes";
import roundRoute from "./rounds/round.routes";
import scheduleRoute from "./schedules/schedule.routes";
import settingsRoute from "./settings/settings.routes";
import syncRoute from "./sync/sync.routes";
import userRoute from "./users/user.routes";
import zonesRoute from "./zones/zones.routes";
import housesRoute from "./houses/houses.routes";
import vehiclesRoute from "./vehicles/vehicles.routes";
import visitorsRoute from "./visitors/visitors.routes";
import accessesRoute from "./accesses/accesses.routes";
import accessLogsRoute from "./access-logs/access-logs.routes";
import complaintsRoute from "./complaints/complaints.routes";
import paymentsRoute from "./payments/payments.routes";
import { handleStripeWebhook } from "./payments/payments.webhook";
import notificationsRoute from "./notifications/notifications.routes";

const apiRouter = Router();

apiRouter.use("/", indexRoute);
apiRouter.use("/home", homeRoute);
apiRouter.use("/users", userRoute);
apiRouter.use("/locations", locationsRoute);
apiRouter.use("/uploads", uploadRoute);
apiRouter.use("/kardex", kardexRoute);
apiRouter.use("/assignments", assignmentsRoute);
apiRouter.use("/incidents", incidentRoute);
apiRouter.use("/rounds", roundRoute);
apiRouter.use("/schedules", scheduleRoute);
apiRouter.use("/maintenance", maintenanceRoute);
apiRouter.use("/reports", reportRoute);
apiRouter.use("/catalog", catalogRoute);
apiRouter.use("/residents", residentsRoute);
apiRouter.use("/contacts", contactsRoute);
apiRouter.use("/zones", zonesRoute);
apiRouter.use("/recurring", recurringRoute);
apiRouter.use("/settings", settingsRoute);
apiRouter.use("/sync", syncRoute);
apiRouter.use("/houses", housesRoute);
apiRouter.use("/vehicles", vehiclesRoute);
apiRouter.use("/visitors", visitorsRoute);
apiRouter.use("/accesses", accessesRoute);
apiRouter.use("/access-logs", accessLogsRoute);
apiRouter.use("/complaints", complaintsRoute);
apiRouter.post("/payments/webhook", handleStripeWebhook);
apiRouter.use("/payments", paymentsRoute);
apiRouter.use("/notifications", notificationsRoute);

export default apiRouter;
